name: Deploy S3

on:
  push:
    branches:
      - live

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Install packages
        run: npm install --legacy-peer-deps

      - name: Build Nuxt
        run: npm run build

      - name: Generate Nuxt static files
        run: npm run generate

      - name: Deploy static site to S3 bucket
        run: aws s3 sync ./dist/ s3://lax.agency --delete
